version: "3"
services:
  postgresql:
    image: "postgres:12.5"
    environment:
      POSTGRES_USER: sportradar
      POSTGRES_PASSWORD: sportradar
      POSTGRES_DB: sportradardb
    expose:
      - "5432"
    ports:
      - "5432:5432"
