version: "2"
services:
  postgresql:
    image: "postgres:12.5"
    environment:
      POSTGRES_USER: sportradar
      POSTGRES_PASSWORD: sportradar
      POSTGRES_DB: sportradardb
    expose:
      - "5432"
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data   
volumes:
  cache:
    driver: local
